"""Initial migration

Revision ID: 083e5b2d2b5e
Revises: 4554661ebfa5
Create Date: 2025-04-24 08:41:19.420210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "083e5b2d2b5e"
down_revision: Union[str, None] = "4554661ebfa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
