"""Initial migration

Revision ID: 4117969e8d0a
Revises: 54e9f6fa8be0
Create Date: 2025-04-24 10:13:03.541155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4117969e8d0a"
down_revision: Union[str, None] = "54e9f6fa8be0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
