"""Initial migration

Revision ID: 608b1ba2313e
Revises: 083e5b2d2b5e
Create Date: 2025-04-24 08:46:00.604391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "608b1ba2313e"
down_revision: Union[str, None] = "083e5b2d2b5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
