"""Initial migration

Revision ID: 74ba9d80b1a3
Revises: d18f6c92a8a4
Create Date: 2025-04-24 06:00:13.700918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74ba9d80b1a3"
down_revision: Union[str, None] = "d18f6c92a8a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
