"""Initial migration

Revision ID: d18f6c92a8a4
Revises: d7ef97b5a785
Create Date: 2025-04-24 05:57:26.784868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d18f6c92a8a4"
down_revision: Union[str, None] = "d7ef97b5a785"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
